name: WakaTime Readme Stats

on:
  workflow_dispatch:
  schedule:
    # Se ejecuta cada 24 horas a medianoche UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Actualizar WakaTime en README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Usamos el SHA de commit para la versión 5, que es extremadamente estable:
      - uses: anmol098/waka-readme-stats@a0280f331f93f631988892d3f2400b6528d22744
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Configuración personalizada
          SECTION_NAME: waka
          COMMIT_BY_ME: "true"
          SHOW_OS: "false"
          SHOW_PROJECTS: "false"
          SHOW_DAYS_OF_WEEK: "false"
